const expect    = require("chai").expect;
const PaserLines = require("../build/PaserLines");
function datos(){
  var result =[];
  result.push("-’ JRE AGENT INTEL MISSIL");
  result.push("");
  result.push("KeIIyKap0wski <");
  result.push("LVL 15");
  result.push("36,301,849 AP 140,000,000 AP");
  result.push("");
  result.push("EEK” g 4/4 02/2");
  result.push("");
  result.push("/ \\");
  result.push("«W» .9 \\");
  result.push("\m/ ,\\");
  result.push("xn");
  result.push(",\ r,\ V");
  result.push("");
  result.push(" ");
  result.push("");
  result.push(" ");
  result.push("");
  result.push("A");
  result.push("V");
  result.push("");
  result.push("@QQQQQ");
  result.push("");
  result.push("ALLTIME 1 MONTH 1 WEEK 1 NOW");
  result.push("");
  result.push("i");
  result.push("");
  result.push("Unique Portals Visited 5,019");
  result.push("Portals Discovered 1");
  result.push("XM Collected 144,700,906 XM");
  result.push("1:");
  result.push("");
  result.push("Distance Walked 2,184 km");
  result.push("1:");
  result.push("");
  result.push("Resonators Deployed 54,719");
  result.push("Links Created 8,896");
  result.push("Control Fields Created 4,747");
  result.push("Mind Units Captured 10,642,121 MUs");
  result.push("Longest Link Ever Created 292 km");
  result.push("Largest Control Field 3,082,190 MUs");
  result.push("XM Recharged 79,158,869 XM");
  result.push("Portals Captured 7,314");
  result.push("Unique Portals Captured 2,955");
  result.push("Mods Deployed 8,844");
  result.push("I");
  result.push("");
  result.push("Resonators Destroyed 34,120");
  result.push("Portals Neutralized 5,316");
  result.push("Enemy Links Destroyed 6,005");
  result.push("Enemy Control Fields Destroyed 3,014");
  result.push("i");
  result.push("");
  result.push("Max Time Portal Held 326 days");
  result.push("Max Time Link Maintained 113 days");
  result.push("Max Link Length x Days 727 km-days");
  result.push("Max Time Field Held 113 days");
  result.push("Largest Field MUs x Days 318,818 MU-days");
  result.push("I");
  result.push("");
  result.push("Unique Missions Completed 42");
  result.push("I");
  result.push("");
  result.push("Hacks 27,202");
  result.push("Glyph Hack Points 98,183");
  result.push("Longest Hacking Streak 426 days");
  result.push("i");
  result.push("");
  result.push("Agents Successfully Recruited 2");

  return result;
}
describe("PaserLines", function() {
    describe("create ProfileAgent", function() {
        it("not null", function() {
            const parserLine = new PaserLines("el reto");
            const as = parserLine.scannerLine(datos());
            console.log(as);
            expect(as).to.equal(null);
        });
    });
});
